[server]
enableStaticServing = true

[theme]
primaryColor = "#116B56"
backgroundColor = "#FAFCF8"
secondaryBackgroundColor = "#E2F4ED"
textColor = "#18332C"
font = "sans serif"

dataframeHeaderTextColor = "#18332C"
dataframeHeaderBackgroundColor = "#E2F4ED"
